---
framework: mocha  
preRun:
  command:
    - npm ci 
preMerge:
  pattern:
    - "./test/acceptance/*.js"
postMerge:
  pattern: 
    - "./test/acceptance/*.js"
postRun:
  command:
    - node --version
configFile: mocharc.yml
version: 1.2
